### ISSUE TITLE
NetSparkle private key is exposed

### ISSUE THREAD

**Issue by Deadpikle** [MinhQuan020903/Dictionary#11]
This repository has a published private key for NetSparkle updates via a GitHub gist. The private key should _never_ be published on the internet to the general public. I would consider your private key to be compromised at this point! Other people can use your private key to push updates out that look like they are yours, and that's bad for obvious reasons.

**Comment by AkiraNoob** [comment]
@Deadpikle thank you for your warning. This is our school project so I first think it would not be a big deal to keep the key secret. It only use for generate signature right? This repository is for learning purpose only.

**Comment by Deadpikle** [comment]
Ah, yeah if it's just for a school project or something that won't be widely distributed beyond your classroom, you're probably ok. :-) Just make sure that if you use NetSparkle in a real/public project in the future to create new keys!
